version: '3'

services:
  elastic:
    image: elasticsearch:7.6.1
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:5000,http://127.0.0.1:5000
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

  elastichq:
    image: elastichq/elasticsearch-hq:release-v3.5.12
    environment:
      - HQ_DEFAULT_URL=http://elastic:9200
      - HQ_DEBUG=True
      - HQ_ENABLE_SSL=True
      - HQ_VERIFY_CERTS=False
      - HQ_CA_CERTS=/usr/local/share/ca-certificates/MYCA.crt
    ports:
    - 5000:5000
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
