version: '3'

services:
  # mongod --httpinterface
  mongodb:
    image: mongo:4.2.3
    ports:
      - 27017:27017
      - 28017:28017
    environment:
      #- MONGO_INITDB_DATABASE=transport
      #- MONGO_INITDB_ROOT_USERNAME=master
      #- MONGO_INITDB_ROOT_PASSWORD=letmein
      - AUTH=no
